import Head from "next/head";
import Image from "next/image";
import styles from "../resources/styles/Home.module.scss";
import { getSession, signOut, useSession } from "next-auth/client";
import { Button } from "@material-ui/core";
import { GetServerSideProps } from "next";
import { Session } from "next-auth";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Landing page</h1>
      </main>
    </div>
  );
}

export const getServerSideProps: GetServerSideProps<{
  session: Session | null;
}> = async (context) => {
  const session = await getSession(context);

  // if(!session) {
  //   return {
  //     redirect: {
  //       permanent: false,
  //       destination: "/auth/signin"
  //     }
  //   }
  // }

  if (session) {
    return {
      redirect: {
        permanent: false,
        destination: "/notes",
      },
    };
  }

  return {
    props: {
      session: session,
    },
  };
};
