import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "../resources/styles/main.scss";
import StyledComponentsRegistry from "@/lib/registry";
import Providers from "@/app/Providers";
import Navbar from "@/components/Navigation/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en" data-theme="light">
        <body className={inter.className}>
          <StyledComponentsRegistry>
            <Navbar>{children}</Navbar>
          </StyledComponentsRegistry>
          <script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>
        </body>
      </html>
    </Providers>
  );
}
